name: my_add
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.2.0
  cross_file: ^0.3.3+2
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.2.2
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.3
  image_picker: ^0.8.6
  intl: ^0.17.0
  motion_toast: ^2.6.4
  uuid: ^3.0.7
  xfile: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
